# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/gogobody/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/193.6494.38/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/gogobody/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/193.6494.38/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gogobody/Documents/Projects/dfs/OpendfsSource

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gogobody/Documents/Projects/dfs/OpendfsSource

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/gogobody/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/193.6494.38/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/gogobody/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/193.6494.38/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gogobody/Documents/Projects/dfs/OpendfsSource/CMakeFiles /home/gogobody/Documents/Projects/dfs/OpendfsSource/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gogobody/Documents/Projects/dfs/OpendfsSource/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named namenode

# Build rule for target.
namenode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 namenode
.PHONY : namenode

# fast build rule for target.
namenode/fast:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/build
.PHONY : namenode/fast

src/cfs/cfs.o: src/cfs/cfs.c.o

.PHONY : src/cfs/cfs.o

# target to build an object file
src/cfs/cfs.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/cfs/cfs.c.o
.PHONY : src/cfs/cfs.c.o

src/cfs/cfs.i: src/cfs/cfs.c.i

.PHONY : src/cfs/cfs.i

# target to preprocess a source file
src/cfs/cfs.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/cfs/cfs.c.i
.PHONY : src/cfs/cfs.c.i

src/cfs/cfs.s: src/cfs/cfs.c.s

.PHONY : src/cfs/cfs.s

# target to generate assembly for a file
src/cfs/cfs.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/cfs/cfs.c.s
.PHONY : src/cfs/cfs.c.s

src/cfs/cfs_eio.o: src/cfs/cfs_eio.c.o

.PHONY : src/cfs/cfs_eio.o

# target to build an object file
src/cfs/cfs_eio.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/cfs/cfs_eio.c.o
.PHONY : src/cfs/cfs_eio.c.o

src/cfs/cfs_eio.i: src/cfs/cfs_eio.c.i

.PHONY : src/cfs/cfs_eio.i

# target to preprocess a source file
src/cfs/cfs_eio.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/cfs/cfs_eio.c.i
.PHONY : src/cfs/cfs_eio.c.i

src/cfs/cfs_eio.s: src/cfs/cfs_eio.c.s

.PHONY : src/cfs/cfs_eio.s

# target to generate assembly for a file
src/cfs/cfs_eio.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/cfs/cfs_eio.c.s
.PHONY : src/cfs/cfs_eio.c.s

src/cfs/cfs_faio.o: src/cfs/cfs_faio.c.o

.PHONY : src/cfs/cfs_faio.o

# target to build an object file
src/cfs/cfs_faio.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/cfs/cfs_faio.c.o
.PHONY : src/cfs/cfs_faio.c.o

src/cfs/cfs_faio.i: src/cfs/cfs_faio.c.i

.PHONY : src/cfs/cfs_faio.i

# target to preprocess a source file
src/cfs/cfs_faio.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/cfs/cfs_faio.c.i
.PHONY : src/cfs/cfs_faio.c.i

src/cfs/cfs_faio.s: src/cfs/cfs_faio.c.s

.PHONY : src/cfs/cfs_faio.s

# target to generate assembly for a file
src/cfs/cfs_faio.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/cfs/cfs_faio.c.s
.PHONY : src/cfs/cfs_faio.c.s

src/cfs/cfs_fio.o: src/cfs/cfs_fio.c.o

.PHONY : src/cfs/cfs_fio.o

# target to build an object file
src/cfs/cfs_fio.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/cfs/cfs_fio.c.o
.PHONY : src/cfs/cfs_fio.c.o

src/cfs/cfs_fio.i: src/cfs/cfs_fio.c.i

.PHONY : src/cfs/cfs_fio.i

# target to preprocess a source file
src/cfs/cfs_fio.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/cfs/cfs_fio.c.i
.PHONY : src/cfs/cfs_fio.c.i

src/cfs/cfs_fio.s: src/cfs/cfs_fio.c.s

.PHONY : src/cfs/cfs_fio.s

# target to generate assembly for a file
src/cfs/cfs_fio.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/cfs/cfs_fio.c.s
.PHONY : src/cfs/cfs_fio.c.s

src/common/dfs_task.o: src/common/dfs_task.c.o

.PHONY : src/common/dfs_task.o

# target to build an object file
src/common/dfs_task.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/common/dfs_task.c.o
.PHONY : src/common/dfs_task.c.o

src/common/dfs_task.i: src/common/dfs_task.c.i

.PHONY : src/common/dfs_task.i

# target to preprocess a source file
src/common/dfs_task.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/common/dfs_task.c.i
.PHONY : src/common/dfs_task.c.i

src/common/dfs_task.s: src/common/dfs_task.c.s

.PHONY : src/common/dfs_task.s

# target to generate assembly for a file
src/common/dfs_task.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/common/dfs_task.c.s
.PHONY : src/common/dfs_task.c.s

src/common/dfs_task_codec.o: src/common/dfs_task_codec.c.o

.PHONY : src/common/dfs_task_codec.o

# target to build an object file
src/common/dfs_task_codec.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/common/dfs_task_codec.c.o
.PHONY : src/common/dfs_task_codec.c.o

src/common/dfs_task_codec.i: src/common/dfs_task_codec.c.i

.PHONY : src/common/dfs_task_codec.i

# target to preprocess a source file
src/common/dfs_task_codec.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/common/dfs_task_codec.c.i
.PHONY : src/common/dfs_task_codec.c.i

src/common/dfs_task_codec.s: src/common/dfs_task_codec.c.s

.PHONY : src/common/dfs_task_codec.s

# target to generate assembly for a file
src/common/dfs_task_codec.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/common/dfs_task_codec.c.s
.PHONY : src/common/dfs_task_codec.c.s

src/common/fs_permission.o: src/common/fs_permission.cpp.o

.PHONY : src/common/fs_permission.o

# target to build an object file
src/common/fs_permission.cpp.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/common/fs_permission.cpp.o
.PHONY : src/common/fs_permission.cpp.o

src/common/fs_permission.i: src/common/fs_permission.cpp.i

.PHONY : src/common/fs_permission.i

# target to preprocess a source file
src/common/fs_permission.cpp.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/common/fs_permission.cpp.i
.PHONY : src/common/fs_permission.cpp.i

src/common/fs_permission.s: src/common/fs_permission.cpp.s

.PHONY : src/common/fs_permission.s

# target to generate assembly for a file
src/common/fs_permission.cpp.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/common/fs_permission.cpp.s
.PHONY : src/common/fs_permission.cpp.s

src/core/dfs_array.o: src/core/dfs_array.c.o

.PHONY : src/core/dfs_array.o

# target to build an object file
src/core/dfs_array.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_array.c.o
.PHONY : src/core/dfs_array.c.o

src/core/dfs_array.i: src/core/dfs_array.c.i

.PHONY : src/core/dfs_array.i

# target to preprocess a source file
src/core/dfs_array.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_array.c.i
.PHONY : src/core/dfs_array.c.i

src/core/dfs_array.s: src/core/dfs_array.c.s

.PHONY : src/core/dfs_array.s

# target to generate assembly for a file
src/core/dfs_array.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_array.c.s
.PHONY : src/core/dfs_array.c.s

src/core/dfs_buffer.o: src/core/dfs_buffer.c.o

.PHONY : src/core/dfs_buffer.o

# target to build an object file
src/core/dfs_buffer.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_buffer.c.o
.PHONY : src/core/dfs_buffer.c.o

src/core/dfs_buffer.i: src/core/dfs_buffer.c.i

.PHONY : src/core/dfs_buffer.i

# target to preprocess a source file
src/core/dfs_buffer.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_buffer.c.i
.PHONY : src/core/dfs_buffer.c.i

src/core/dfs_buffer.s: src/core/dfs_buffer.c.s

.PHONY : src/core/dfs_buffer.s

# target to generate assembly for a file
src/core/dfs_buffer.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_buffer.c.s
.PHONY : src/core/dfs_buffer.c.s

src/core/dfs_chain.o: src/core/dfs_chain.c.o

.PHONY : src/core/dfs_chain.o

# target to build an object file
src/core/dfs_chain.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_chain.c.o
.PHONY : src/core/dfs_chain.c.o

src/core/dfs_chain.i: src/core/dfs_chain.c.i

.PHONY : src/core/dfs_chain.i

# target to preprocess a source file
src/core/dfs_chain.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_chain.c.i
.PHONY : src/core/dfs_chain.c.i

src/core/dfs_chain.s: src/core/dfs_chain.c.s

.PHONY : src/core/dfs_chain.s

# target to generate assembly for a file
src/core/dfs_chain.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_chain.c.s
.PHONY : src/core/dfs_chain.c.s

src/core/dfs_channel.o: src/core/dfs_channel.c.o

.PHONY : src/core/dfs_channel.o

# target to build an object file
src/core/dfs_channel.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_channel.c.o
.PHONY : src/core/dfs_channel.c.o

src/core/dfs_channel.i: src/core/dfs_channel.c.i

.PHONY : src/core/dfs_channel.i

# target to preprocess a source file
src/core/dfs_channel.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_channel.c.i
.PHONY : src/core/dfs_channel.c.i

src/core/dfs_channel.s: src/core/dfs_channel.c.s

.PHONY : src/core/dfs_channel.s

# target to generate assembly for a file
src/core/dfs_channel.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_channel.c.s
.PHONY : src/core/dfs_channel.c.s

src/core/dfs_commpool.o: src/core/dfs_commpool.c.o

.PHONY : src/core/dfs_commpool.o

# target to build an object file
src/core/dfs_commpool.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_commpool.c.o
.PHONY : src/core/dfs_commpool.c.o

src/core/dfs_commpool.i: src/core/dfs_commpool.c.i

.PHONY : src/core/dfs_commpool.i

# target to preprocess a source file
src/core/dfs_commpool.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_commpool.c.i
.PHONY : src/core/dfs_commpool.c.i

src/core/dfs_commpool.s: src/core/dfs_commpool.c.s

.PHONY : src/core/dfs_commpool.s

# target to generate assembly for a file
src/core/dfs_commpool.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_commpool.c.s
.PHONY : src/core/dfs_commpool.c.s

src/core/dfs_commpool_allocator.o: src/core/dfs_commpool_allocator.c.o

.PHONY : src/core/dfs_commpool_allocator.o

# target to build an object file
src/core/dfs_commpool_allocator.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_commpool_allocator.c.o
.PHONY : src/core/dfs_commpool_allocator.c.o

src/core/dfs_commpool_allocator.i: src/core/dfs_commpool_allocator.c.i

.PHONY : src/core/dfs_commpool_allocator.i

# target to preprocess a source file
src/core/dfs_commpool_allocator.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_commpool_allocator.c.i
.PHONY : src/core/dfs_commpool_allocator.c.i

src/core/dfs_commpool_allocator.s: src/core/dfs_commpool_allocator.c.s

.PHONY : src/core/dfs_commpool_allocator.s

# target to generate assembly for a file
src/core/dfs_commpool_allocator.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_commpool_allocator.c.s
.PHONY : src/core/dfs_commpool_allocator.c.s

src/core/dfs_conf.o: src/core/dfs_conf.c.o

.PHONY : src/core/dfs_conf.o

# target to build an object file
src/core/dfs_conf.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conf.c.o
.PHONY : src/core/dfs_conf.c.o

src/core/dfs_conf.i: src/core/dfs_conf.c.i

.PHONY : src/core/dfs_conf.i

# target to preprocess a source file
src/core/dfs_conf.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conf.c.i
.PHONY : src/core/dfs_conf.c.i

src/core/dfs_conf.s: src/core/dfs_conf.c.s

.PHONY : src/core/dfs_conf.s

# target to generate assembly for a file
src/core/dfs_conf.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conf.c.s
.PHONY : src/core/dfs_conf.c.s

src/core/dfs_conf_base.o: src/core/dfs_conf_base.c.o

.PHONY : src/core/dfs_conf_base.o

# target to build an object file
src/core/dfs_conf_base.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conf_base.c.o
.PHONY : src/core/dfs_conf_base.c.o

src/core/dfs_conf_base.i: src/core/dfs_conf_base.c.i

.PHONY : src/core/dfs_conf_base.i

# target to preprocess a source file
src/core/dfs_conf_base.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conf_base.c.i
.PHONY : src/core/dfs_conf_base.c.i

src/core/dfs_conf_base.s: src/core/dfs_conf_base.c.s

.PHONY : src/core/dfs_conf_base.s

# target to generate assembly for a file
src/core/dfs_conf_base.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conf_base.c.s
.PHONY : src/core/dfs_conf_base.c.s

src/core/dfs_conn.o: src/core/dfs_conn.c.o

.PHONY : src/core/dfs_conn.o

# target to build an object file
src/core/dfs_conn.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conn.c.o
.PHONY : src/core/dfs_conn.c.o

src/core/dfs_conn.i: src/core/dfs_conn.c.i

.PHONY : src/core/dfs_conn.i

# target to preprocess a source file
src/core/dfs_conn.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conn.c.i
.PHONY : src/core/dfs_conn.c.i

src/core/dfs_conn.s: src/core/dfs_conn.c.s

.PHONY : src/core/dfs_conn.s

# target to generate assembly for a file
src/core/dfs_conn.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conn.c.s
.PHONY : src/core/dfs_conn.c.s

src/core/dfs_conn_listen.o: src/core/dfs_conn_listen.c.o

.PHONY : src/core/dfs_conn_listen.o

# target to build an object file
src/core/dfs_conn_listen.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conn_listen.c.o
.PHONY : src/core/dfs_conn_listen.c.o

src/core/dfs_conn_listen.i: src/core/dfs_conn_listen.c.i

.PHONY : src/core/dfs_conn_listen.i

# target to preprocess a source file
src/core/dfs_conn_listen.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conn_listen.c.i
.PHONY : src/core/dfs_conn_listen.c.i

src/core/dfs_conn_listen.s: src/core/dfs_conn_listen.c.s

.PHONY : src/core/dfs_conn_listen.s

# target to generate assembly for a file
src/core/dfs_conn_listen.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conn_listen.c.s
.PHONY : src/core/dfs_conn_listen.c.s

src/core/dfs_conn_pool.o: src/core/dfs_conn_pool.c.o

.PHONY : src/core/dfs_conn_pool.o

# target to build an object file
src/core/dfs_conn_pool.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conn_pool.c.o
.PHONY : src/core/dfs_conn_pool.c.o

src/core/dfs_conn_pool.i: src/core/dfs_conn_pool.c.i

.PHONY : src/core/dfs_conn_pool.i

# target to preprocess a source file
src/core/dfs_conn_pool.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conn_pool.c.i
.PHONY : src/core/dfs_conn_pool.c.i

src/core/dfs_conn_pool.s: src/core/dfs_conn_pool.c.s

.PHONY : src/core/dfs_conn_pool.s

# target to generate assembly for a file
src/core/dfs_conn_pool.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_conn_pool.c.s
.PHONY : src/core/dfs_conn_pool.c.s

src/core/dfs_epoll.o: src/core/dfs_epoll.c.o

.PHONY : src/core/dfs_epoll.o

# target to build an object file
src/core/dfs_epoll.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_epoll.c.o
.PHONY : src/core/dfs_epoll.c.o

src/core/dfs_epoll.i: src/core/dfs_epoll.c.i

.PHONY : src/core/dfs_epoll.i

# target to preprocess a source file
src/core/dfs_epoll.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_epoll.c.i
.PHONY : src/core/dfs_epoll.c.i

src/core/dfs_epoll.s: src/core/dfs_epoll.c.s

.PHONY : src/core/dfs_epoll.s

# target to generate assembly for a file
src/core/dfs_epoll.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_epoll.c.s
.PHONY : src/core/dfs_epoll.c.s

src/core/dfs_error_log.o: src/core/dfs_error_log.c.o

.PHONY : src/core/dfs_error_log.o

# target to build an object file
src/core/dfs_error_log.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_error_log.c.o
.PHONY : src/core/dfs_error_log.c.o

src/core/dfs_error_log.i: src/core/dfs_error_log.c.i

.PHONY : src/core/dfs_error_log.i

# target to preprocess a source file
src/core/dfs_error_log.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_error_log.c.i
.PHONY : src/core/dfs_error_log.c.i

src/core/dfs_error_log.s: src/core/dfs_error_log.c.s

.PHONY : src/core/dfs_error_log.s

# target to generate assembly for a file
src/core/dfs_error_log.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_error_log.c.s
.PHONY : src/core/dfs_error_log.c.s

src/core/dfs_event.o: src/core/dfs_event.c.o

.PHONY : src/core/dfs_event.o

# target to build an object file
src/core/dfs_event.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_event.c.o
.PHONY : src/core/dfs_event.c.o

src/core/dfs_event.i: src/core/dfs_event.c.i

.PHONY : src/core/dfs_event.i

# target to preprocess a source file
src/core/dfs_event.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_event.c.i
.PHONY : src/core/dfs_event.c.i

src/core/dfs_event.s: src/core/dfs_event.c.s

.PHONY : src/core/dfs_event.s

# target to generate assembly for a file
src/core/dfs_event.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_event.c.s
.PHONY : src/core/dfs_event.c.s

src/core/dfs_event_timer.o: src/core/dfs_event_timer.c.o

.PHONY : src/core/dfs_event_timer.o

# target to build an object file
src/core/dfs_event_timer.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_event_timer.c.o
.PHONY : src/core/dfs_event_timer.c.o

src/core/dfs_event_timer.i: src/core/dfs_event_timer.c.i

.PHONY : src/core/dfs_event_timer.i

# target to preprocess a source file
src/core/dfs_event_timer.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_event_timer.c.i
.PHONY : src/core/dfs_event_timer.c.i

src/core/dfs_event_timer.s: src/core/dfs_event_timer.c.s

.PHONY : src/core/dfs_event_timer.s

# target to generate assembly for a file
src/core/dfs_event_timer.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_event_timer.c.s
.PHONY : src/core/dfs_event_timer.c.s

src/core/dfs_half_life_mempool.o: src/core/dfs_half_life_mempool.c.o

.PHONY : src/core/dfs_half_life_mempool.o

# target to build an object file
src/core/dfs_half_life_mempool.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_half_life_mempool.c.o
.PHONY : src/core/dfs_half_life_mempool.c.o

src/core/dfs_half_life_mempool.i: src/core/dfs_half_life_mempool.c.i

.PHONY : src/core/dfs_half_life_mempool.i

# target to preprocess a source file
src/core/dfs_half_life_mempool.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_half_life_mempool.c.i
.PHONY : src/core/dfs_half_life_mempool.c.i

src/core/dfs_half_life_mempool.s: src/core/dfs_half_life_mempool.c.s

.PHONY : src/core/dfs_half_life_mempool.s

# target to generate assembly for a file
src/core/dfs_half_life_mempool.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_half_life_mempool.c.s
.PHONY : src/core/dfs_half_life_mempool.c.s

src/core/dfs_hashtable.o: src/core/dfs_hashtable.c.o

.PHONY : src/core/dfs_hashtable.o

# target to build an object file
src/core/dfs_hashtable.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_hashtable.c.o
.PHONY : src/core/dfs_hashtable.c.o

src/core/dfs_hashtable.i: src/core/dfs_hashtable.c.i

.PHONY : src/core/dfs_hashtable.i

# target to preprocess a source file
src/core/dfs_hashtable.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_hashtable.c.i
.PHONY : src/core/dfs_hashtable.c.i

src/core/dfs_hashtable.s: src/core/dfs_hashtable.c.s

.PHONY : src/core/dfs_hashtable.s

# target to generate assembly for a file
src/core/dfs_hashtable.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_hashtable.c.s
.PHONY : src/core/dfs_hashtable.c.s

src/core/dfs_ipc.o: src/core/dfs_ipc.c.o

.PHONY : src/core/dfs_ipc.o

# target to build an object file
src/core/dfs_ipc.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_ipc.c.o
.PHONY : src/core/dfs_ipc.c.o

src/core/dfs_ipc.i: src/core/dfs_ipc.c.i

.PHONY : src/core/dfs_ipc.i

# target to preprocess a source file
src/core/dfs_ipc.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_ipc.c.i
.PHONY : src/core/dfs_ipc.c.i

src/core/dfs_ipc.s: src/core/dfs_ipc.c.s

.PHONY : src/core/dfs_ipc.s

# target to generate assembly for a file
src/core/dfs_ipc.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_ipc.c.s
.PHONY : src/core/dfs_ipc.c.s

src/core/dfs_list.o: src/core/dfs_list.c.o

.PHONY : src/core/dfs_list.o

# target to build an object file
src/core/dfs_list.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_list.c.o
.PHONY : src/core/dfs_list.c.o

src/core/dfs_list.i: src/core/dfs_list.c.i

.PHONY : src/core/dfs_list.i

# target to preprocess a source file
src/core/dfs_list.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_list.c.i
.PHONY : src/core/dfs_list.c.i

src/core/dfs_list.s: src/core/dfs_list.c.s

.PHONY : src/core/dfs_list.s

# target to generate assembly for a file
src/core/dfs_list.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_list.c.s
.PHONY : src/core/dfs_list.c.s

src/core/dfs_lock.o: src/core/dfs_lock.c.o

.PHONY : src/core/dfs_lock.o

# target to build an object file
src/core/dfs_lock.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_lock.c.o
.PHONY : src/core/dfs_lock.c.o

src/core/dfs_lock.i: src/core/dfs_lock.c.i

.PHONY : src/core/dfs_lock.i

# target to preprocess a source file
src/core/dfs_lock.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_lock.c.i
.PHONY : src/core/dfs_lock.c.i

src/core/dfs_lock.s: src/core/dfs_lock.c.s

.PHONY : src/core/dfs_lock.s

# target to generate assembly for a file
src/core/dfs_lock.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_lock.c.s
.PHONY : src/core/dfs_lock.c.s

src/core/dfs_math.o: src/core/dfs_math.c.o

.PHONY : src/core/dfs_math.o

# target to build an object file
src/core/dfs_math.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_math.c.o
.PHONY : src/core/dfs_math.c.o

src/core/dfs_math.i: src/core/dfs_math.c.i

.PHONY : src/core/dfs_math.i

# target to preprocess a source file
src/core/dfs_math.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_math.c.i
.PHONY : src/core/dfs_math.c.i

src/core/dfs_math.s: src/core/dfs_math.c.s

.PHONY : src/core/dfs_math.s

# target to generate assembly for a file
src/core/dfs_math.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_math.c.s
.PHONY : src/core/dfs_math.c.s

src/core/dfs_mblks.o: src/core/dfs_mblks.c.o

.PHONY : src/core/dfs_mblks.o

# target to build an object file
src/core/dfs_mblks.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_mblks.c.o
.PHONY : src/core/dfs_mblks.c.o

src/core/dfs_mblks.i: src/core/dfs_mblks.c.i

.PHONY : src/core/dfs_mblks.i

# target to preprocess a source file
src/core/dfs_mblks.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_mblks.c.i
.PHONY : src/core/dfs_mblks.c.i

src/core/dfs_mblks.s: src/core/dfs_mblks.c.s

.PHONY : src/core/dfs_mblks.s

# target to generate assembly for a file
src/core/dfs_mblks.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_mblks.c.s
.PHONY : src/core/dfs_mblks.c.s

src/core/dfs_mem_allocator.o: src/core/dfs_mem_allocator.c.o

.PHONY : src/core/dfs_mem_allocator.o

# target to build an object file
src/core/dfs_mem_allocator.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_mem_allocator.c.o
.PHONY : src/core/dfs_mem_allocator.c.o

src/core/dfs_mem_allocator.i: src/core/dfs_mem_allocator.c.i

.PHONY : src/core/dfs_mem_allocator.i

# target to preprocess a source file
src/core/dfs_mem_allocator.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_mem_allocator.c.i
.PHONY : src/core/dfs_mem_allocator.c.i

src/core/dfs_mem_allocator.s: src/core/dfs_mem_allocator.c.s

.PHONY : src/core/dfs_mem_allocator.s

# target to generate assembly for a file
src/core/dfs_mem_allocator.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_mem_allocator.c.s
.PHONY : src/core/dfs_mem_allocator.c.s

src/core/dfs_memory.o: src/core/dfs_memory.c.o

.PHONY : src/core/dfs_memory.o

# target to build an object file
src/core/dfs_memory.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_memory.c.o
.PHONY : src/core/dfs_memory.c.o

src/core/dfs_memory.i: src/core/dfs_memory.c.i

.PHONY : src/core/dfs_memory.i

# target to preprocess a source file
src/core/dfs_memory.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_memory.c.i
.PHONY : src/core/dfs_memory.c.i

src/core/dfs_memory.s: src/core/dfs_memory.c.s

.PHONY : src/core/dfs_memory.s

# target to generate assembly for a file
src/core/dfs_memory.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_memory.c.s
.PHONY : src/core/dfs_memory.c.s

src/core/dfs_memory_pool.o: src/core/dfs_memory_pool.c.o

.PHONY : src/core/dfs_memory_pool.o

# target to build an object file
src/core/dfs_memory_pool.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_memory_pool.c.o
.PHONY : src/core/dfs_memory_pool.c.o

src/core/dfs_memory_pool.i: src/core/dfs_memory_pool.c.i

.PHONY : src/core/dfs_memory_pool.i

# target to preprocess a source file
src/core/dfs_memory_pool.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_memory_pool.c.i
.PHONY : src/core/dfs_memory_pool.c.i

src/core/dfs_memory_pool.s: src/core/dfs_memory_pool.c.s

.PHONY : src/core/dfs_memory_pool.s

# target to generate assembly for a file
src/core/dfs_memory_pool.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_memory_pool.c.s
.PHONY : src/core/dfs_memory_pool.c.s

src/core/dfs_mempool_allocator.o: src/core/dfs_mempool_allocator.c.o

.PHONY : src/core/dfs_mempool_allocator.o

# target to build an object file
src/core/dfs_mempool_allocator.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_mempool_allocator.c.o
.PHONY : src/core/dfs_mempool_allocator.c.o

src/core/dfs_mempool_allocator.i: src/core/dfs_mempool_allocator.c.i

.PHONY : src/core/dfs_mempool_allocator.i

# target to preprocess a source file
src/core/dfs_mempool_allocator.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_mempool_allocator.c.i
.PHONY : src/core/dfs_mempool_allocator.c.i

src/core/dfs_mempool_allocator.s: src/core/dfs_mempool_allocator.c.s

.PHONY : src/core/dfs_mempool_allocator.s

# target to generate assembly for a file
src/core/dfs_mempool_allocator.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_mempool_allocator.c.s
.PHONY : src/core/dfs_mempool_allocator.c.s

src/core/dfs_notice.o: src/core/dfs_notice.c.o

.PHONY : src/core/dfs_notice.o

# target to build an object file
src/core/dfs_notice.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_notice.c.o
.PHONY : src/core/dfs_notice.c.o

src/core/dfs_notice.i: src/core/dfs_notice.c.i

.PHONY : src/core/dfs_notice.i

# target to preprocess a source file
src/core/dfs_notice.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_notice.c.i
.PHONY : src/core/dfs_notice.c.i

src/core/dfs_notice.s: src/core/dfs_notice.c.s

.PHONY : src/core/dfs_notice.s

# target to generate assembly for a file
src/core/dfs_notice.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_notice.c.s
.PHONY : src/core/dfs_notice.c.s

src/core/dfs_pipe.o: src/core/dfs_pipe.c.o

.PHONY : src/core/dfs_pipe.o

# target to build an object file
src/core/dfs_pipe.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_pipe.c.o
.PHONY : src/core/dfs_pipe.c.o

src/core/dfs_pipe.i: src/core/dfs_pipe.c.i

.PHONY : src/core/dfs_pipe.i

# target to preprocess a source file
src/core/dfs_pipe.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_pipe.c.i
.PHONY : src/core/dfs_pipe.c.i

src/core/dfs_pipe.s: src/core/dfs_pipe.c.s

.PHONY : src/core/dfs_pipe.s

# target to generate assembly for a file
src/core/dfs_pipe.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_pipe.c.s
.PHONY : src/core/dfs_pipe.c.s

src/core/dfs_queue.o: src/core/dfs_queue.c.o

.PHONY : src/core/dfs_queue.o

# target to build an object file
src/core/dfs_queue.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_queue.c.o
.PHONY : src/core/dfs_queue.c.o

src/core/dfs_queue.i: src/core/dfs_queue.c.i

.PHONY : src/core/dfs_queue.i

# target to preprocess a source file
src/core/dfs_queue.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_queue.c.i
.PHONY : src/core/dfs_queue.c.i

src/core/dfs_queue.s: src/core/dfs_queue.c.s

.PHONY : src/core/dfs_queue.s

# target to generate assembly for a file
src/core/dfs_queue.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_queue.c.s
.PHONY : src/core/dfs_queue.c.s

src/core/dfs_rbtree.o: src/core/dfs_rbtree.c.o

.PHONY : src/core/dfs_rbtree.o

# target to build an object file
src/core/dfs_rbtree.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_rbtree.c.o
.PHONY : src/core/dfs_rbtree.c.o

src/core/dfs_rbtree.i: src/core/dfs_rbtree.c.i

.PHONY : src/core/dfs_rbtree.i

# target to preprocess a source file
src/core/dfs_rbtree.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_rbtree.c.i
.PHONY : src/core/dfs_rbtree.c.i

src/core/dfs_rbtree.s: src/core/dfs_rbtree.c.s

.PHONY : src/core/dfs_rbtree.s

# target to generate assembly for a file
src/core/dfs_rbtree.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_rbtree.c.s
.PHONY : src/core/dfs_rbtree.c.s

src/core/dfs_shmem.o: src/core/dfs_shmem.c.o

.PHONY : src/core/dfs_shmem.o

# target to build an object file
src/core/dfs_shmem.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_shmem.c.o
.PHONY : src/core/dfs_shmem.c.o

src/core/dfs_shmem.i: src/core/dfs_shmem.c.i

.PHONY : src/core/dfs_shmem.i

# target to preprocess a source file
src/core/dfs_shmem.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_shmem.c.i
.PHONY : src/core/dfs_shmem.c.i

src/core/dfs_shmem.s: src/core/dfs_shmem.c.s

.PHONY : src/core/dfs_shmem.s

# target to generate assembly for a file
src/core/dfs_shmem.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_shmem.c.s
.PHONY : src/core/dfs_shmem.c.s

src/core/dfs_shmem_allocator.o: src/core/dfs_shmem_allocator.c.o

.PHONY : src/core/dfs_shmem_allocator.o

# target to build an object file
src/core/dfs_shmem_allocator.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_shmem_allocator.c.o
.PHONY : src/core/dfs_shmem_allocator.c.o

src/core/dfs_shmem_allocator.i: src/core/dfs_shmem_allocator.c.i

.PHONY : src/core/dfs_shmem_allocator.i

# target to preprocess a source file
src/core/dfs_shmem_allocator.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_shmem_allocator.c.i
.PHONY : src/core/dfs_shmem_allocator.c.i

src/core/dfs_shmem_allocator.s: src/core/dfs_shmem_allocator.c.s

.PHONY : src/core/dfs_shmem_allocator.s

# target to generate assembly for a file
src/core/dfs_shmem_allocator.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_shmem_allocator.c.s
.PHONY : src/core/dfs_shmem_allocator.c.s

src/core/dfs_slabs.o: src/core/dfs_slabs.c.o

.PHONY : src/core/dfs_slabs.o

# target to build an object file
src/core/dfs_slabs.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_slabs.c.o
.PHONY : src/core/dfs_slabs.c.o

src/core/dfs_slabs.i: src/core/dfs_slabs.c.i

.PHONY : src/core/dfs_slabs.i

# target to preprocess a source file
src/core/dfs_slabs.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_slabs.c.i
.PHONY : src/core/dfs_slabs.c.i

src/core/dfs_slabs.s: src/core/dfs_slabs.c.s

.PHONY : src/core/dfs_slabs.s

# target to generate assembly for a file
src/core/dfs_slabs.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_slabs.c.s
.PHONY : src/core/dfs_slabs.c.s

src/core/dfs_string.o: src/core/dfs_string.c.o

.PHONY : src/core/dfs_string.o

# target to build an object file
src/core/dfs_string.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_string.c.o
.PHONY : src/core/dfs_string.c.o

src/core/dfs_string.i: src/core/dfs_string.c.i

.PHONY : src/core/dfs_string.i

# target to preprocess a source file
src/core/dfs_string.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_string.c.i
.PHONY : src/core/dfs_string.c.i

src/core/dfs_string.s: src/core/dfs_string.c.s

.PHONY : src/core/dfs_string.s

# target to generate assembly for a file
src/core/dfs_string.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_string.c.s
.PHONY : src/core/dfs_string.c.s

src/core/dfs_sys.o: src/core/dfs_sys.c.o

.PHONY : src/core/dfs_sys.o

# target to build an object file
src/core/dfs_sys.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_sys.c.o
.PHONY : src/core/dfs_sys.c.o

src/core/dfs_sys.i: src/core/dfs_sys.c.i

.PHONY : src/core/dfs_sys.i

# target to preprocess a source file
src/core/dfs_sys.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_sys.c.i
.PHONY : src/core/dfs_sys.c.i

src/core/dfs_sys.s: src/core/dfs_sys.c.s

.PHONY : src/core/dfs_sys.s

# target to generate assembly for a file
src/core/dfs_sys.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_sys.c.s
.PHONY : src/core/dfs_sys.c.s

src/core/dfs_sysio.o: src/core/dfs_sysio.c.o

.PHONY : src/core/dfs_sysio.o

# target to build an object file
src/core/dfs_sysio.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_sysio.c.o
.PHONY : src/core/dfs_sysio.c.o

src/core/dfs_sysio.i: src/core/dfs_sysio.c.i

.PHONY : src/core/dfs_sysio.i

# target to preprocess a source file
src/core/dfs_sysio.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_sysio.c.i
.PHONY : src/core/dfs_sysio.c.i

src/core/dfs_sysio.s: src/core/dfs_sysio.c.s

.PHONY : src/core/dfs_sysio.s

# target to generate assembly for a file
src/core/dfs_sysio.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_sysio.c.s
.PHONY : src/core/dfs_sysio.c.s

src/core/dfs_time.o: src/core/dfs_time.c.o

.PHONY : src/core/dfs_time.o

# target to build an object file
src/core/dfs_time.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_time.c.o
.PHONY : src/core/dfs_time.c.o

src/core/dfs_time.i: src/core/dfs_time.c.i

.PHONY : src/core/dfs_time.i

# target to preprocess a source file
src/core/dfs_time.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_time.c.i
.PHONY : src/core/dfs_time.c.i

src/core/dfs_time.s: src/core/dfs_time.c.s

.PHONY : src/core/dfs_time.s

# target to generate assembly for a file
src/core/dfs_time.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/core/dfs_time.c.s
.PHONY : src/core/dfs_time.c.s

src/faio/faio_atomic_lock.o: src/faio/faio_atomic_lock.c.o

.PHONY : src/faio/faio_atomic_lock.o

# target to build an object file
src/faio/faio_atomic_lock.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_atomic_lock.c.o
.PHONY : src/faio/faio_atomic_lock.c.o

src/faio/faio_atomic_lock.i: src/faio/faio_atomic_lock.c.i

.PHONY : src/faio/faio_atomic_lock.i

# target to preprocess a source file
src/faio/faio_atomic_lock.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_atomic_lock.c.i
.PHONY : src/faio/faio_atomic_lock.c.i

src/faio/faio_atomic_lock.s: src/faio/faio_atomic_lock.c.s

.PHONY : src/faio/faio_atomic_lock.s

# target to generate assembly for a file
src/faio/faio_atomic_lock.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_atomic_lock.c.s
.PHONY : src/faio/faio_atomic_lock.c.s

src/faio/faio_data_manager.o: src/faio/faio_data_manager.c.o

.PHONY : src/faio/faio_data_manager.o

# target to build an object file
src/faio/faio_data_manager.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_data_manager.c.o
.PHONY : src/faio/faio_data_manager.c.o

src/faio/faio_data_manager.i: src/faio/faio_data_manager.c.i

.PHONY : src/faio/faio_data_manager.i

# target to preprocess a source file
src/faio/faio_data_manager.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_data_manager.c.i
.PHONY : src/faio/faio_data_manager.c.i

src/faio/faio_data_manager.s: src/faio/faio_data_manager.c.s

.PHONY : src/faio/faio_data_manager.s

# target to generate assembly for a file
src/faio/faio_data_manager.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_data_manager.c.s
.PHONY : src/faio/faio_data_manager.c.s

src/faio/faio_error.o: src/faio/faio_error.c.o

.PHONY : src/faio/faio_error.o

# target to build an object file
src/faio/faio_error.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_error.c.o
.PHONY : src/faio/faio_error.c.o

src/faio/faio_error.i: src/faio/faio_error.c.i

.PHONY : src/faio/faio_error.i

# target to preprocess a source file
src/faio/faio_error.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_error.c.i
.PHONY : src/faio/faio_error.c.i

src/faio/faio_error.s: src/faio/faio_error.c.s

.PHONY : src/faio/faio_error.s

# target to generate assembly for a file
src/faio/faio_error.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_error.c.s
.PHONY : src/faio/faio_error.c.s

src/faio/faio_handler_manager.o: src/faio/faio_handler_manager.c.o

.PHONY : src/faio/faio_handler_manager.o

# target to build an object file
src/faio/faio_handler_manager.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_handler_manager.c.o
.PHONY : src/faio/faio_handler_manager.c.o

src/faio/faio_handler_manager.i: src/faio/faio_handler_manager.c.i

.PHONY : src/faio/faio_handler_manager.i

# target to preprocess a source file
src/faio/faio_handler_manager.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_handler_manager.c.i
.PHONY : src/faio/faio_handler_manager.c.i

src/faio/faio_handler_manager.s: src/faio/faio_handler_manager.c.s

.PHONY : src/faio/faio_handler_manager.s

# target to generate assembly for a file
src/faio/faio_handler_manager.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_handler_manager.c.s
.PHONY : src/faio/faio_handler_manager.c.s

src/faio/faio_manager.o: src/faio/faio_manager.c.o

.PHONY : src/faio/faio_manager.o

# target to build an object file
src/faio/faio_manager.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_manager.c.o
.PHONY : src/faio/faio_manager.c.o

src/faio/faio_manager.i: src/faio/faio_manager.c.i

.PHONY : src/faio/faio_manager.i

# target to preprocess a source file
src/faio/faio_manager.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_manager.c.i
.PHONY : src/faio/faio_manager.c.i

src/faio/faio_manager.s: src/faio/faio_manager.c.s

.PHONY : src/faio/faio_manager.s

# target to generate assembly for a file
src/faio/faio_manager.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_manager.c.s
.PHONY : src/faio/faio_manager.c.s

src/faio/faio_notifier_manager.o: src/faio/faio_notifier_manager.c.o

.PHONY : src/faio/faio_notifier_manager.o

# target to build an object file
src/faio/faio_notifier_manager.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_notifier_manager.c.o
.PHONY : src/faio/faio_notifier_manager.c.o

src/faio/faio_notifier_manager.i: src/faio/faio_notifier_manager.c.i

.PHONY : src/faio/faio_notifier_manager.i

# target to preprocess a source file
src/faio/faio_notifier_manager.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_notifier_manager.c.i
.PHONY : src/faio/faio_notifier_manager.c.i

src/faio/faio_notifier_manager.s: src/faio/faio_notifier_manager.c.s

.PHONY : src/faio/faio_notifier_manager.s

# target to generate assembly for a file
src/faio/faio_notifier_manager.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_notifier_manager.c.s
.PHONY : src/faio/faio_notifier_manager.c.s

src/faio/faio_thread.o: src/faio/faio_thread.c.o

.PHONY : src/faio/faio_thread.o

# target to build an object file
src/faio/faio_thread.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_thread.c.o
.PHONY : src/faio/faio_thread.c.o

src/faio/faio_thread.i: src/faio/faio_thread.c.i

.PHONY : src/faio/faio_thread.i

# target to preprocess a source file
src/faio/faio_thread.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_thread.c.i
.PHONY : src/faio/faio_thread.c.i

src/faio/faio_thread.s: src/faio/faio_thread.c.s

.PHONY : src/faio/faio_thread.s

# target to generate assembly for a file
src/faio/faio_thread.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_thread.c.s
.PHONY : src/faio/faio_thread.c.s

src/faio/faio_worker_manager.o: src/faio/faio_worker_manager.c.o

.PHONY : src/faio/faio_worker_manager.o

# target to build an object file
src/faio/faio_worker_manager.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_worker_manager.c.o
.PHONY : src/faio/faio_worker_manager.c.o

src/faio/faio_worker_manager.i: src/faio/faio_worker_manager.c.i

.PHONY : src/faio/faio_worker_manager.i

# target to preprocess a source file
src/faio/faio_worker_manager.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_worker_manager.c.i
.PHONY : src/faio/faio_worker_manager.c.i

src/faio/faio_worker_manager.s: src/faio/faio_worker_manager.c.s

.PHONY : src/faio/faio_worker_manager.s

# target to generate assembly for a file
src/faio/faio_worker_manager.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/faio/faio_worker_manager.c.s
.PHONY : src/faio/faio_worker_manager.c.s

src/namenode/nn_blk_index.o: src/namenode/nn_blk_index.c.o

.PHONY : src/namenode/nn_blk_index.o

# target to build an object file
src/namenode/nn_blk_index.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_blk_index.c.o
.PHONY : src/namenode/nn_blk_index.c.o

src/namenode/nn_blk_index.i: src/namenode/nn_blk_index.c.i

.PHONY : src/namenode/nn_blk_index.i

# target to preprocess a source file
src/namenode/nn_blk_index.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_blk_index.c.i
.PHONY : src/namenode/nn_blk_index.c.i

src/namenode/nn_blk_index.s: src/namenode/nn_blk_index.c.s

.PHONY : src/namenode/nn_blk_index.s

# target to generate assembly for a file
src/namenode/nn_blk_index.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_blk_index.c.s
.PHONY : src/namenode/nn_blk_index.c.s

src/namenode/nn_conf.o: src/namenode/nn_conf.c.o

.PHONY : src/namenode/nn_conf.o

# target to build an object file
src/namenode/nn_conf.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_conf.c.o
.PHONY : src/namenode/nn_conf.c.o

src/namenode/nn_conf.i: src/namenode/nn_conf.c.i

.PHONY : src/namenode/nn_conf.i

# target to preprocess a source file
src/namenode/nn_conf.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_conf.c.i
.PHONY : src/namenode/nn_conf.c.i

src/namenode/nn_conf.s: src/namenode/nn_conf.c.s

.PHONY : src/namenode/nn_conf.s

# target to generate assembly for a file
src/namenode/nn_conf.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_conf.c.s
.PHONY : src/namenode/nn_conf.c.s

src/namenode/nn_conn_event.o: src/namenode/nn_conn_event.c.o

.PHONY : src/namenode/nn_conn_event.o

# target to build an object file
src/namenode/nn_conn_event.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_conn_event.c.o
.PHONY : src/namenode/nn_conn_event.c.o

src/namenode/nn_conn_event.i: src/namenode/nn_conn_event.c.i

.PHONY : src/namenode/nn_conn_event.i

# target to preprocess a source file
src/namenode/nn_conn_event.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_conn_event.c.i
.PHONY : src/namenode/nn_conn_event.c.i

src/namenode/nn_conn_event.s: src/namenode/nn_conn_event.c.s

.PHONY : src/namenode/nn_conn_event.s

# target to generate assembly for a file
src/namenode/nn_conn_event.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_conn_event.c.s
.PHONY : src/namenode/nn_conn_event.c.s

src/namenode/nn_cycle.o: src/namenode/nn_cycle.c.o

.PHONY : src/namenode/nn_cycle.o

# target to build an object file
src/namenode/nn_cycle.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_cycle.c.o
.PHONY : src/namenode/nn_cycle.c.o

src/namenode/nn_cycle.i: src/namenode/nn_cycle.c.i

.PHONY : src/namenode/nn_cycle.i

# target to preprocess a source file
src/namenode/nn_cycle.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_cycle.c.i
.PHONY : src/namenode/nn_cycle.c.i

src/namenode/nn_cycle.s: src/namenode/nn_cycle.c.s

.PHONY : src/namenode/nn_cycle.s

# target to generate assembly for a file
src/namenode/nn_cycle.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_cycle.c.s
.PHONY : src/namenode/nn_cycle.c.s

src/namenode/nn_dn_index.o: src/namenode/nn_dn_index.c.o

.PHONY : src/namenode/nn_dn_index.o

# target to build an object file
src/namenode/nn_dn_index.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_dn_index.c.o
.PHONY : src/namenode/nn_dn_index.c.o

src/namenode/nn_dn_index.i: src/namenode/nn_dn_index.c.i

.PHONY : src/namenode/nn_dn_index.i

# target to preprocess a source file
src/namenode/nn_dn_index.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_dn_index.c.i
.PHONY : src/namenode/nn_dn_index.c.i

src/namenode/nn_dn_index.s: src/namenode/nn_dn_index.c.s

.PHONY : src/namenode/nn_dn_index.s

# target to generate assembly for a file
src/namenode/nn_dn_index.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_dn_index.c.s
.PHONY : src/namenode/nn_dn_index.c.s

src/namenode/nn_error_log.o: src/namenode/nn_error_log.c.o

.PHONY : src/namenode/nn_error_log.o

# target to build an object file
src/namenode/nn_error_log.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_error_log.c.o
.PHONY : src/namenode/nn_error_log.c.o

src/namenode/nn_error_log.i: src/namenode/nn_error_log.c.i

.PHONY : src/namenode/nn_error_log.i

# target to preprocess a source file
src/namenode/nn_error_log.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_error_log.c.i
.PHONY : src/namenode/nn_error_log.c.i

src/namenode/nn_error_log.s: src/namenode/nn_error_log.c.s

.PHONY : src/namenode/nn_error_log.s

# target to generate assembly for a file
src/namenode/nn_error_log.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_error_log.c.s
.PHONY : src/namenode/nn_error_log.c.s

src/namenode/nn_file_index.o: src/namenode/nn_file_index.c.o

.PHONY : src/namenode/nn_file_index.o

# target to build an object file
src/namenode/nn_file_index.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_file_index.c.o
.PHONY : src/namenode/nn_file_index.c.o

src/namenode/nn_file_index.i: src/namenode/nn_file_index.c.i

.PHONY : src/namenode/nn_file_index.i

# target to preprocess a source file
src/namenode/nn_file_index.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_file_index.c.i
.PHONY : src/namenode/nn_file_index.c.i

src/namenode/nn_file_index.s: src/namenode/nn_file_index.c.s

.PHONY : src/namenode/nn_file_index.s

# target to generate assembly for a file
src/namenode/nn_file_index.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_file_index.c.s
.PHONY : src/namenode/nn_file_index.c.s

src/namenode/nn_main.o: src/namenode/nn_main.c.o

.PHONY : src/namenode/nn_main.o

# target to build an object file
src/namenode/nn_main.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_main.c.o
.PHONY : src/namenode/nn_main.c.o

src/namenode/nn_main.i: src/namenode/nn_main.c.i

.PHONY : src/namenode/nn_main.i

# target to preprocess a source file
src/namenode/nn_main.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_main.c.i
.PHONY : src/namenode/nn_main.c.i

src/namenode/nn_main.s: src/namenode/nn_main.c.s

.PHONY : src/namenode/nn_main.s

# target to generate assembly for a file
src/namenode/nn_main.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_main.c.s
.PHONY : src/namenode/nn_main.c.s

src/namenode/nn_module.o: src/namenode/nn_module.c.o

.PHONY : src/namenode/nn_module.o

# target to build an object file
src/namenode/nn_module.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_module.c.o
.PHONY : src/namenode/nn_module.c.o

src/namenode/nn_module.i: src/namenode/nn_module.c.i

.PHONY : src/namenode/nn_module.i

# target to preprocess a source file
src/namenode/nn_module.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_module.c.i
.PHONY : src/namenode/nn_module.c.i

src/namenode/nn_module.s: src/namenode/nn_module.c.s

.PHONY : src/namenode/nn_module.s

# target to generate assembly for a file
src/namenode/nn_module.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_module.c.s
.PHONY : src/namenode/nn_module.c.s

src/namenode/nn_net_response_handler.o: src/namenode/nn_net_response_handler.c.o

.PHONY : src/namenode/nn_net_response_handler.o

# target to build an object file
src/namenode/nn_net_response_handler.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_net_response_handler.c.o
.PHONY : src/namenode/nn_net_response_handler.c.o

src/namenode/nn_net_response_handler.i: src/namenode/nn_net_response_handler.c.i

.PHONY : src/namenode/nn_net_response_handler.i

# target to preprocess a source file
src/namenode/nn_net_response_handler.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_net_response_handler.c.i
.PHONY : src/namenode/nn_net_response_handler.c.i

src/namenode/nn_net_response_handler.s: src/namenode/nn_net_response_handler.c.s

.PHONY : src/namenode/nn_net_response_handler.s

# target to generate assembly for a file
src/namenode/nn_net_response_handler.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_net_response_handler.c.s
.PHONY : src/namenode/nn_net_response_handler.c.s

src/namenode/nn_paxos.o: src/namenode/nn_paxos.c.o

.PHONY : src/namenode/nn_paxos.o

# target to build an object file
src/namenode/nn_paxos.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_paxos.c.o
.PHONY : src/namenode/nn_paxos.c.o

src/namenode/nn_paxos.i: src/namenode/nn_paxos.c.i

.PHONY : src/namenode/nn_paxos.i

# target to preprocess a source file
src/namenode/nn_paxos.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_paxos.c.i
.PHONY : src/namenode/nn_paxos.c.i

src/namenode/nn_paxos.s: src/namenode/nn_paxos.c.s

.PHONY : src/namenode/nn_paxos.s

# target to generate assembly for a file
src/namenode/nn_paxos.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_paxos.c.s
.PHONY : src/namenode/nn_paxos.c.s

src/namenode/nn_process.o: src/namenode/nn_process.c.o

.PHONY : src/namenode/nn_process.o

# target to build an object file
src/namenode/nn_process.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_process.c.o
.PHONY : src/namenode/nn_process.c.o

src/namenode/nn_process.i: src/namenode/nn_process.c.i

.PHONY : src/namenode/nn_process.i

# target to preprocess a source file
src/namenode/nn_process.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_process.c.i
.PHONY : src/namenode/nn_process.c.i

src/namenode/nn_process.s: src/namenode/nn_process.c.s

.PHONY : src/namenode/nn_process.s

# target to generate assembly for a file
src/namenode/nn_process.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_process.c.s
.PHONY : src/namenode/nn_process.c.s

src/namenode/nn_request.o: src/namenode/nn_request.c.o

.PHONY : src/namenode/nn_request.o

# target to build an object file
src/namenode/nn_request.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_request.c.o
.PHONY : src/namenode/nn_request.c.o

src/namenode/nn_request.i: src/namenode/nn_request.c.i

.PHONY : src/namenode/nn_request.i

# target to preprocess a source file
src/namenode/nn_request.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_request.c.i
.PHONY : src/namenode/nn_request.c.i

src/namenode/nn_request.s: src/namenode/nn_request.c.s

.PHONY : src/namenode/nn_request.s

# target to generate assembly for a file
src/namenode/nn_request.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_request.c.s
.PHONY : src/namenode/nn_request.c.s

src/namenode/nn_rpc_server.o: src/namenode/nn_rpc_server.c.o

.PHONY : src/namenode/nn_rpc_server.o

# target to build an object file
src/namenode/nn_rpc_server.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_rpc_server.c.o
.PHONY : src/namenode/nn_rpc_server.c.o

src/namenode/nn_rpc_server.i: src/namenode/nn_rpc_server.c.i

.PHONY : src/namenode/nn_rpc_server.i

# target to preprocess a source file
src/namenode/nn_rpc_server.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_rpc_server.c.i
.PHONY : src/namenode/nn_rpc_server.c.i

src/namenode/nn_rpc_server.s: src/namenode/nn_rpc_server.c.s

.PHONY : src/namenode/nn_rpc_server.s

# target to generate assembly for a file
src/namenode/nn_rpc_server.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_rpc_server.c.s
.PHONY : src/namenode/nn_rpc_server.c.s

src/namenode/nn_signal.o: src/namenode/nn_signal.c.o

.PHONY : src/namenode/nn_signal.o

# target to build an object file
src/namenode/nn_signal.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_signal.c.o
.PHONY : src/namenode/nn_signal.c.o

src/namenode/nn_signal.i: src/namenode/nn_signal.c.i

.PHONY : src/namenode/nn_signal.i

# target to preprocess a source file
src/namenode/nn_signal.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_signal.c.i
.PHONY : src/namenode/nn_signal.c.i

src/namenode/nn_signal.s: src/namenode/nn_signal.c.s

.PHONY : src/namenode/nn_signal.s

# target to generate assembly for a file
src/namenode/nn_signal.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_signal.c.s
.PHONY : src/namenode/nn_signal.c.s

src/namenode/nn_task_handler.o: src/namenode/nn_task_handler.c.o

.PHONY : src/namenode/nn_task_handler.o

# target to build an object file
src/namenode/nn_task_handler.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_task_handler.c.o
.PHONY : src/namenode/nn_task_handler.c.o

src/namenode/nn_task_handler.i: src/namenode/nn_task_handler.c.i

.PHONY : src/namenode/nn_task_handler.i

# target to preprocess a source file
src/namenode/nn_task_handler.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_task_handler.c.i
.PHONY : src/namenode/nn_task_handler.c.i

src/namenode/nn_task_handler.s: src/namenode/nn_task_handler.c.s

.PHONY : src/namenode/nn_task_handler.s

# target to generate assembly for a file
src/namenode/nn_task_handler.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_task_handler.c.s
.PHONY : src/namenode/nn_task_handler.c.s

src/namenode/nn_task_queue.o: src/namenode/nn_task_queue.c.o

.PHONY : src/namenode/nn_task_queue.o

# target to build an object file
src/namenode/nn_task_queue.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_task_queue.c.o
.PHONY : src/namenode/nn_task_queue.c.o

src/namenode/nn_task_queue.i: src/namenode/nn_task_queue.c.i

.PHONY : src/namenode/nn_task_queue.i

# target to preprocess a source file
src/namenode/nn_task_queue.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_task_queue.c.i
.PHONY : src/namenode/nn_task_queue.c.i

src/namenode/nn_task_queue.s: src/namenode/nn_task_queue.c.s

.PHONY : src/namenode/nn_task_queue.s

# target to generate assembly for a file
src/namenode/nn_task_queue.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_task_queue.c.s
.PHONY : src/namenode/nn_task_queue.c.s

src/namenode/nn_thread.o: src/namenode/nn_thread.c.o

.PHONY : src/namenode/nn_thread.o

# target to build an object file
src/namenode/nn_thread.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_thread.c.o
.PHONY : src/namenode/nn_thread.c.o

src/namenode/nn_thread.i: src/namenode/nn_thread.c.i

.PHONY : src/namenode/nn_thread.i

# target to preprocess a source file
src/namenode/nn_thread.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_thread.c.i
.PHONY : src/namenode/nn_thread.c.i

src/namenode/nn_thread.s: src/namenode/nn_thread.c.s

.PHONY : src/namenode/nn_thread.s

# target to generate assembly for a file
src/namenode/nn_thread.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_thread.c.s
.PHONY : src/namenode/nn_thread.c.s

src/namenode/nn_time.o: src/namenode/nn_time.c.o

.PHONY : src/namenode/nn_time.o

# target to build an object file
src/namenode/nn_time.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_time.c.o
.PHONY : src/namenode/nn_time.c.o

src/namenode/nn_time.i: src/namenode/nn_time.c.i

.PHONY : src/namenode/nn_time.i

# target to preprocess a source file
src/namenode/nn_time.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_time.c.i
.PHONY : src/namenode/nn_time.c.i

src/namenode/nn_time.s: src/namenode/nn_time.c.s

.PHONY : src/namenode/nn_time.s

# target to generate assembly for a file
src/namenode/nn_time.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_time.c.s
.PHONY : src/namenode/nn_time.c.s

src/namenode/nn_worker_process.o: src/namenode/nn_worker_process.c.o

.PHONY : src/namenode/nn_worker_process.o

# target to build an object file
src/namenode/nn_worker_process.c.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_worker_process.c.o
.PHONY : src/namenode/nn_worker_process.c.o

src/namenode/nn_worker_process.i: src/namenode/nn_worker_process.c.i

.PHONY : src/namenode/nn_worker_process.i

# target to preprocess a source file
src/namenode/nn_worker_process.c.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_worker_process.c.i
.PHONY : src/namenode/nn_worker_process.c.i

src/namenode/nn_worker_process.s: src/namenode/nn_worker_process.c.s

.PHONY : src/namenode/nn_worker_process.s

# target to generate assembly for a file
src/namenode/nn_worker_process.c.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/namenode/nn_worker_process.c.s
.PHONY : src/namenode/nn_worker_process.c.s

src/paxos/EditlogSM.o: src/paxos/EditlogSM.cpp.o

.PHONY : src/paxos/EditlogSM.o

# target to build an object file
src/paxos/EditlogSM.cpp.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/paxos/EditlogSM.cpp.o
.PHONY : src/paxos/EditlogSM.cpp.o

src/paxos/EditlogSM.i: src/paxos/EditlogSM.cpp.i

.PHONY : src/paxos/EditlogSM.i

# target to preprocess a source file
src/paxos/EditlogSM.cpp.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/paxos/EditlogSM.cpp.i
.PHONY : src/paxos/EditlogSM.cpp.i

src/paxos/EditlogSM.s: src/paxos/EditlogSM.cpp.s

.PHONY : src/paxos/EditlogSM.s

# target to generate assembly for a file
src/paxos/EditlogSM.cpp.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/paxos/EditlogSM.cpp.s
.PHONY : src/paxos/EditlogSM.cpp.s

src/paxos/FSEditlog.o: src/paxos/FSEditlog.cpp.o

.PHONY : src/paxos/FSEditlog.o

# target to build an object file
src/paxos/FSEditlog.cpp.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/paxos/FSEditlog.cpp.o
.PHONY : src/paxos/FSEditlog.cpp.o

src/paxos/FSEditlog.i: src/paxos/FSEditlog.cpp.i

.PHONY : src/paxos/FSEditlog.i

# target to preprocess a source file
src/paxos/FSEditlog.cpp.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/paxos/FSEditlog.cpp.i
.PHONY : src/paxos/FSEditlog.cpp.i

src/paxos/FSEditlog.s: src/paxos/FSEditlog.cpp.s

.PHONY : src/paxos/FSEditlog.s

# target to generate assembly for a file
src/paxos/FSEditlog.cpp.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/paxos/FSEditlog.cpp.s
.PHONY : src/paxos/FSEditlog.cpp.s

src/paxos/phxeditlog.pb.o: src/paxos/phxeditlog.pb.cpp.o

.PHONY : src/paxos/phxeditlog.pb.o

# target to build an object file
src/paxos/phxeditlog.pb.cpp.o:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/paxos/phxeditlog.pb.cpp.o
.PHONY : src/paxos/phxeditlog.pb.cpp.o

src/paxos/phxeditlog.pb.i: src/paxos/phxeditlog.pb.cpp.i

.PHONY : src/paxos/phxeditlog.pb.i

# target to preprocess a source file
src/paxos/phxeditlog.pb.cpp.i:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/paxos/phxeditlog.pb.cpp.i
.PHONY : src/paxos/phxeditlog.pb.cpp.i

src/paxos/phxeditlog.pb.s: src/paxos/phxeditlog.pb.cpp.s

.PHONY : src/paxos/phxeditlog.pb.s

# target to generate assembly for a file
src/paxos/phxeditlog.pb.cpp.s:
	$(MAKE) -f CMakeFiles/namenode.dir/build.make CMakeFiles/namenode.dir/src/paxos/phxeditlog.pb.cpp.s
.PHONY : src/paxos/phxeditlog.pb.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... namenode"
	@echo "... edit_cache"
	@echo "... src/cfs/cfs.o"
	@echo "... src/cfs/cfs.i"
	@echo "... src/cfs/cfs.s"
	@echo "... src/cfs/cfs_eio.o"
	@echo "... src/cfs/cfs_eio.i"
	@echo "... src/cfs/cfs_eio.s"
	@echo "... src/cfs/cfs_faio.o"
	@echo "... src/cfs/cfs_faio.i"
	@echo "... src/cfs/cfs_faio.s"
	@echo "... src/cfs/cfs_fio.o"
	@echo "... src/cfs/cfs_fio.i"
	@echo "... src/cfs/cfs_fio.s"
	@echo "... src/common/dfs_task.o"
	@echo "... src/common/dfs_task.i"
	@echo "... src/common/dfs_task.s"
	@echo "... src/common/dfs_task_codec.o"
	@echo "... src/common/dfs_task_codec.i"
	@echo "... src/common/dfs_task_codec.s"
	@echo "... src/common/fs_permission.o"
	@echo "... src/common/fs_permission.i"
	@echo "... src/common/fs_permission.s"
	@echo "... src/core/dfs_array.o"
	@echo "... src/core/dfs_array.i"
	@echo "... src/core/dfs_array.s"
	@echo "... src/core/dfs_buffer.o"
	@echo "... src/core/dfs_buffer.i"
	@echo "... src/core/dfs_buffer.s"
	@echo "... src/core/dfs_chain.o"
	@echo "... src/core/dfs_chain.i"
	@echo "... src/core/dfs_chain.s"
	@echo "... src/core/dfs_channel.o"
	@echo "... src/core/dfs_channel.i"
	@echo "... src/core/dfs_channel.s"
	@echo "... src/core/dfs_commpool.o"
	@echo "... src/core/dfs_commpool.i"
	@echo "... src/core/dfs_commpool.s"
	@echo "... src/core/dfs_commpool_allocator.o"
	@echo "... src/core/dfs_commpool_allocator.i"
	@echo "... src/core/dfs_commpool_allocator.s"
	@echo "... src/core/dfs_conf.o"
	@echo "... src/core/dfs_conf.i"
	@echo "... src/core/dfs_conf.s"
	@echo "... src/core/dfs_conf_base.o"
	@echo "... src/core/dfs_conf_base.i"
	@echo "... src/core/dfs_conf_base.s"
	@echo "... src/core/dfs_conn.o"
	@echo "... src/core/dfs_conn.i"
	@echo "... src/core/dfs_conn.s"
	@echo "... src/core/dfs_conn_listen.o"
	@echo "... src/core/dfs_conn_listen.i"
	@echo "... src/core/dfs_conn_listen.s"
	@echo "... src/core/dfs_conn_pool.o"
	@echo "... src/core/dfs_conn_pool.i"
	@echo "... src/core/dfs_conn_pool.s"
	@echo "... src/core/dfs_epoll.o"
	@echo "... src/core/dfs_epoll.i"
	@echo "... src/core/dfs_epoll.s"
	@echo "... src/core/dfs_error_log.o"
	@echo "... src/core/dfs_error_log.i"
	@echo "... src/core/dfs_error_log.s"
	@echo "... src/core/dfs_event.o"
	@echo "... src/core/dfs_event.i"
	@echo "... src/core/dfs_event.s"
	@echo "... src/core/dfs_event_timer.o"
	@echo "... src/core/dfs_event_timer.i"
	@echo "... src/core/dfs_event_timer.s"
	@echo "... src/core/dfs_half_life_mempool.o"
	@echo "... src/core/dfs_half_life_mempool.i"
	@echo "... src/core/dfs_half_life_mempool.s"
	@echo "... src/core/dfs_hashtable.o"
	@echo "... src/core/dfs_hashtable.i"
	@echo "... src/core/dfs_hashtable.s"
	@echo "... src/core/dfs_ipc.o"
	@echo "... src/core/dfs_ipc.i"
	@echo "... src/core/dfs_ipc.s"
	@echo "... src/core/dfs_list.o"
	@echo "... src/core/dfs_list.i"
	@echo "... src/core/dfs_list.s"
	@echo "... src/core/dfs_lock.o"
	@echo "... src/core/dfs_lock.i"
	@echo "... src/core/dfs_lock.s"
	@echo "... src/core/dfs_math.o"
	@echo "... src/core/dfs_math.i"
	@echo "... src/core/dfs_math.s"
	@echo "... src/core/dfs_mblks.o"
	@echo "... src/core/dfs_mblks.i"
	@echo "... src/core/dfs_mblks.s"
	@echo "... src/core/dfs_mem_allocator.o"
	@echo "... src/core/dfs_mem_allocator.i"
	@echo "... src/core/dfs_mem_allocator.s"
	@echo "... src/core/dfs_memory.o"
	@echo "... src/core/dfs_memory.i"
	@echo "... src/core/dfs_memory.s"
	@echo "... src/core/dfs_memory_pool.o"
	@echo "... src/core/dfs_memory_pool.i"
	@echo "... src/core/dfs_memory_pool.s"
	@echo "... src/core/dfs_mempool_allocator.o"
	@echo "... src/core/dfs_mempool_allocator.i"
	@echo "... src/core/dfs_mempool_allocator.s"
	@echo "... src/core/dfs_notice.o"
	@echo "... src/core/dfs_notice.i"
	@echo "... src/core/dfs_notice.s"
	@echo "... src/core/dfs_pipe.o"
	@echo "... src/core/dfs_pipe.i"
	@echo "... src/core/dfs_pipe.s"
	@echo "... src/core/dfs_queue.o"
	@echo "... src/core/dfs_queue.i"
	@echo "... src/core/dfs_queue.s"
	@echo "... src/core/dfs_rbtree.o"
	@echo "... src/core/dfs_rbtree.i"
	@echo "... src/core/dfs_rbtree.s"
	@echo "... src/core/dfs_shmem.o"
	@echo "... src/core/dfs_shmem.i"
	@echo "... src/core/dfs_shmem.s"
	@echo "... src/core/dfs_shmem_allocator.o"
	@echo "... src/core/dfs_shmem_allocator.i"
	@echo "... src/core/dfs_shmem_allocator.s"
	@echo "... src/core/dfs_slabs.o"
	@echo "... src/core/dfs_slabs.i"
	@echo "... src/core/dfs_slabs.s"
	@echo "... src/core/dfs_string.o"
	@echo "... src/core/dfs_string.i"
	@echo "... src/core/dfs_string.s"
	@echo "... src/core/dfs_sys.o"
	@echo "... src/core/dfs_sys.i"
	@echo "... src/core/dfs_sys.s"
	@echo "... src/core/dfs_sysio.o"
	@echo "... src/core/dfs_sysio.i"
	@echo "... src/core/dfs_sysio.s"
	@echo "... src/core/dfs_time.o"
	@echo "... src/core/dfs_time.i"
	@echo "... src/core/dfs_time.s"
	@echo "... src/faio/faio_atomic_lock.o"
	@echo "... src/faio/faio_atomic_lock.i"
	@echo "... src/faio/faio_atomic_lock.s"
	@echo "... src/faio/faio_data_manager.o"
	@echo "... src/faio/faio_data_manager.i"
	@echo "... src/faio/faio_data_manager.s"
	@echo "... src/faio/faio_error.o"
	@echo "... src/faio/faio_error.i"
	@echo "... src/faio/faio_error.s"
	@echo "... src/faio/faio_handler_manager.o"
	@echo "... src/faio/faio_handler_manager.i"
	@echo "... src/faio/faio_handler_manager.s"
	@echo "... src/faio/faio_manager.o"
	@echo "... src/faio/faio_manager.i"
	@echo "... src/faio/faio_manager.s"
	@echo "... src/faio/faio_notifier_manager.o"
	@echo "... src/faio/faio_notifier_manager.i"
	@echo "... src/faio/faio_notifier_manager.s"
	@echo "... src/faio/faio_thread.o"
	@echo "... src/faio/faio_thread.i"
	@echo "... src/faio/faio_thread.s"
	@echo "... src/faio/faio_worker_manager.o"
	@echo "... src/faio/faio_worker_manager.i"
	@echo "... src/faio/faio_worker_manager.s"
	@echo "... src/namenode/nn_blk_index.o"
	@echo "... src/namenode/nn_blk_index.i"
	@echo "... src/namenode/nn_blk_index.s"
	@echo "... src/namenode/nn_conf.o"
	@echo "... src/namenode/nn_conf.i"
	@echo "... src/namenode/nn_conf.s"
	@echo "... src/namenode/nn_conn_event.o"
	@echo "... src/namenode/nn_conn_event.i"
	@echo "... src/namenode/nn_conn_event.s"
	@echo "... src/namenode/nn_cycle.o"
	@echo "... src/namenode/nn_cycle.i"
	@echo "... src/namenode/nn_cycle.s"
	@echo "... src/namenode/nn_dn_index.o"
	@echo "... src/namenode/nn_dn_index.i"
	@echo "... src/namenode/nn_dn_index.s"
	@echo "... src/namenode/nn_error_log.o"
	@echo "... src/namenode/nn_error_log.i"
	@echo "... src/namenode/nn_error_log.s"
	@echo "... src/namenode/nn_file_index.o"
	@echo "... src/namenode/nn_file_index.i"
	@echo "... src/namenode/nn_file_index.s"
	@echo "... src/namenode/nn_main.o"
	@echo "... src/namenode/nn_main.i"
	@echo "... src/namenode/nn_main.s"
	@echo "... src/namenode/nn_module.o"
	@echo "... src/namenode/nn_module.i"
	@echo "... src/namenode/nn_module.s"
	@echo "... src/namenode/nn_net_response_handler.o"
	@echo "... src/namenode/nn_net_response_handler.i"
	@echo "... src/namenode/nn_net_response_handler.s"
	@echo "... src/namenode/nn_paxos.o"
	@echo "... src/namenode/nn_paxos.i"
	@echo "... src/namenode/nn_paxos.s"
	@echo "... src/namenode/nn_process.o"
	@echo "... src/namenode/nn_process.i"
	@echo "... src/namenode/nn_process.s"
	@echo "... src/namenode/nn_request.o"
	@echo "... src/namenode/nn_request.i"
	@echo "... src/namenode/nn_request.s"
	@echo "... src/namenode/nn_rpc_server.o"
	@echo "... src/namenode/nn_rpc_server.i"
	@echo "... src/namenode/nn_rpc_server.s"
	@echo "... src/namenode/nn_signal.o"
	@echo "... src/namenode/nn_signal.i"
	@echo "... src/namenode/nn_signal.s"
	@echo "... src/namenode/nn_task_handler.o"
	@echo "... src/namenode/nn_task_handler.i"
	@echo "... src/namenode/nn_task_handler.s"
	@echo "... src/namenode/nn_task_queue.o"
	@echo "... src/namenode/nn_task_queue.i"
	@echo "... src/namenode/nn_task_queue.s"
	@echo "... src/namenode/nn_thread.o"
	@echo "... src/namenode/nn_thread.i"
	@echo "... src/namenode/nn_thread.s"
	@echo "... src/namenode/nn_time.o"
	@echo "... src/namenode/nn_time.i"
	@echo "... src/namenode/nn_time.s"
	@echo "... src/namenode/nn_worker_process.o"
	@echo "... src/namenode/nn_worker_process.i"
	@echo "... src/namenode/nn_worker_process.s"
	@echo "... src/paxos/EditlogSM.o"
	@echo "... src/paxos/EditlogSM.i"
	@echo "... src/paxos/EditlogSM.s"
	@echo "... src/paxos/FSEditlog.o"
	@echo "... src/paxos/FSEditlog.i"
	@echo "... src/paxos/FSEditlog.s"
	@echo "... src/paxos/phxeditlog.pb.o"
	@echo "... src/paxos/phxeditlog.pb.i"
	@echo "... src/paxos/phxeditlog.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

